version: '3.9'

services:
  app:
    build: 
      context: ./  # Diretório onde está o Dockerfile da sua aplicação
    container_name: app_service
    environment:
      DATABASE_URL: postgresql://teste:teste@postgres:5432/teste
      MONGO_URI: mongodb://your_user:your_password@mongodb:27017/
    depends_on:
      - postgres
      - mongodb
    ports:
      - "8083:8000"  # Altere para a porta que seu app usa
    restart: always

  postgres:
    image: postgres:latest
    container_name: postgres_db
    environment:
      POSTGRES_USER: teste
      POSTGRES_PASSWORD: teste
      POSTGRES_DB: teste
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"  # Alterado para 5433 na máquina host
    restart: always

  mongodb:
    image: mongo:latest
    container_name: mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: your_user          
      MONGO_INITDB_ROOT_PASSWORD: your_password      
    volumes:
      - mongo_data:/data/db
    ports:
      - "27017:27017"
    restart: always

volumes:
  postgres_data:
  mongo_data:
